# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: RMB Informática
email: renato@rmbinformatica.net 
description: >- # this means to ignore newlines until "baseurl:"
  RMB Informática, Serviços de informática em Natal - RN, Serviços de TI, Tecnologia da Informação Segurança da informação, Desenvolvimento de sites, Desenvolvimento web, Desenvolvimento de aplicações web, Desenvolvimento de software, Hospedagem de sites, Hospedagem de e-mails, Hospedagem web, Hospedagem de dados, Hospedagem Cloud, Processamento de dados, Tratamento de dados, Cloud Computing, Computação em nuvem, Testes de invasão, Redes de computadores, Monitoramento de redes.
baseurl: "" # the subpath of your site, e.g. /blog
url: "rmbinformatica.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: rmbinformatica
github_username:  rmbinformatica
google_analytics: UA-12891293-4

# Build settings
markdown: kramdown
theme: minima
permalink: /:categories/:title
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
